### ISSUE TITLE
Codesandbox Demo is Broken -> Requires React 16.11

### ISSUE THREAD

**Issue by antoineblueberry** [rajinwonderland/react-code-blocks#1]
This is an awesome project, thanks for making it. Just wanted to give you a heads up the codesandbox demo is broken, you just need to change package.json to point to a more recent version of react. (I changed it to 16.8 for example and it worked)

<img width="1218" alt="Screen Shot 2019-11-02 at 5 53 06 PM" src="https://user-images.githubusercontent.com/45185173/68078737-d365d280-fd99-11e9-896b-86f16c6b117a.png">

**Comment by rajinwonderland** [comment]
Hey @antoineblueberry! Thanks for this! I'll go ahead and make the update.

Thanks!
