### ISSUE TITLE
Cannot run on react 17 + typescript

### ISSUE THREAD

**Issue by quentin-decre** [rajinwonderland/react-code-blocks#123]
I have not been able to make the CopyBlock run :

![image](https://github.com/rajinwonderland/react-code-blocks/assets/1137511/380f0baf-ff6e-4066-a8c4-a492b3f880d9)

And when ignoring the ts error, it fail at runtime :

![image](https://github.com/rajinwonderland/react-code-blocks/assets/1137511/b7345ed6-34dc-4759-9932-7a6e4802f45d)

Any idea ?

**Comment by DavidCibin** [comment]
Kind of the same here. I can use CodeBlock just fine, but not the CopyBlock
A simple test like this works fine
`<CodeBlock
    text="HELLO WORLD"
/>`


But this, I get the a warning described below:
`<CopyBlock
    text="HELLO WORLD"
/>`

`TS2322: Type '{ text: string; }' is not assignable to type 'IntrinsicAttributes & ExecutionProps & RefAttributes<({ theme, text, codeBlock, customStyle, onCopy, ...rest }: CopyBlockProps) => Element>'.   Property 'text' does not exist on type 'IntrinsicAttributes & ExecutionProps & RefAttributes<({ theme, text, codeBlock, customStyle, onCopy, ...rest }: CopyBlockProps) => Element>'.`

I tried the version 0.1.4, 0.1.3 and then I went with the version as the one in the "CodeSandBox" which is the 0.0.8, and only this last one worked for me

**Comment by xyba1337** [comment]
> Kind of the same here. I can use CodeBlock just fine, but not the CopyBlock A simple test like this works fine `<CodeBlock text="HELLO WORLD" />`
> 
> But this, I get the warning below: `<CopyBlock text="HELLO WORLD" />`
> 
> `TS2322: Type '{ text: string; }' is not assignable to type 'IntrinsicAttributes & ExecutionProps & RefAttributes<({ theme, text, codeBlock, customStyle, onCopy, ...rest }: CopyBlockProps) => Element>'. Property 'text' does not exist on type 'IntrinsicAttributes & ExecutionProps & RefAttributes<({ theme, text, codeBlock, customStyle, onCopy, ...rest }: CopyBlockProps) => Element>'.`
> 
> I tried the version 0.1.4, 0.1.3 and then I went with the version as the one in the "CodeSandBox" which is the 0.0.8, and only this last one worked for me

If you're using nextjs >13.5.3 I highly advice you to not use the solution regarding the downgraded version, this just broke my entire project.

**Comment by Fae-Bell** [comment]
Pass in a theme. There is no default theme set.

It will still error in your IDE because there's a bug with how the properties are set up on the CopyBlock, but it will at least work. The error being that most props aren't optional, and the `.d.ts` is using: `import("react").ForwardRefExoticComponent<import("styled-components").ExecutionProps & import("react").RefAttributes<typeof CopyBlock>> & {};`

Both `ExecutionProps` and `CopyBlock` have a theme prop, and theme is optional in one, but required in the other

**Comment by thomasmost** [comment]
Hi y'all — I'm aware that this is an issue and will try and work on a fix this week. It's a bit of an arcane typing thing with the latest versions of Next and TS.

Very sorry for the inconvenience

**Comment by thomasmost** [comment]
I believe I've resolved this as of v0.1.5 — can someone confirm?

**Comment by thomasmost** [comment]
Finally got the fix published — again, sorry for the delay

**Comment by Fae-Bell** [comment]
Just to say it; The typescript issue I was seeing is fixed now. Looks like the types are set up properly.
