### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by HamadTheIronside** [rajinwonderland/react-code-blocks#13]
Hey @rajinwonderland 
So I've been using your component in my Gatsby/MDX project and I love it.
I would love to contribute to the gatsby and how to use it section.

thanks for your awesome repo, I really appreciate it

**Comment by rajinwonderland** [comment]
Hey @HamadTheIronside!

That would be amazing! I'd love for you to contribute!! 🎉

I'd suggest making a PR with a new markdown file that documents your usage as a start.

How would that sound?

**Comment by HamadTheIronside** [comment]
Awesome, I'll start as soon as possible.
