### ISSUE TITLE
Npm page is not updated

### ISSUE THREAD

**Issue by mourra950** [rajinwonderland/react-code-blocks#141]
the page of the library is missing most of the md files and not updated so its confusing unless you open the github page here to read what you need so when i click the supported languages link in the description there i am taken to 404 page
![image](https://github.com/rajinwonderland/react-code-blocks/assets/64339763/ad4a68fc-b6ae-4bad-8d5f-062e36d3869a)
![image](https://github.com/rajinwonderland/react-code-blocks/assets/64339763/53940711-1070-4a8a-8d21-a5899488547b)

**Comment by thomasmost** [comment]
@rajinwonderland I would have thought NPM just reflected the current state of the README — is there a manual step to update the npm page?

**Comment by rajinwonderland** [comment]
Hmm, I would've thought the same. I'll try to update it with a patch tonight

**Comment by rajinwonderland** [comment]
Just checked the [npm page](https://www.npmjs.com/package/react-code-blocks), and it seems to have the readme displaying correctly. 

![image](https://github.com/rajinwonderland/react-code-blocks/assets/15880596/fd1b7ac5-0ac3-4c82-bd78-f9c35a9b3cf3)


@thomasmost @mourra950 Would you mind confirming?

**Comment by thomasmost** [comment]
Doesn't look like it has the latest maintainer info (my contact) or the contributors section

**Comment by thomasmost** [comment]
@rajinwonderland NPM is still not showing the latest version of the README

https://www.npmjs.com/package/react-code-blocks

**Comment by rajinwonderland** [comment]
@thomasmost I'll push another update to see if that fixes it!

**Comment by rajinwonderland** [comment]
@thomasmost README has been updated. In the future, we'll need to update any changes we'd like to see reflected on the npm page's README within the `packages/react-code-blocks/README.md` file. The root README.md file does not get uploaded to the npm page.

**Comment by thomasmost** [comment]
oh that makes sense! thanks @rajinwonderland
