### ISSUE TITLE
FYI package used in Next Right Now! =D

### ISSUE THREAD

**Issue by Vadorequest** [rajinwonderland/react-code-blocks#15]
🎉 Just for your information, I had decided to use your package in Next Right Now and it's what's been featuring code examples for a few months already 😉 

Demo: https://nrn-v2-mst-aptd-at-lcz-sty-c1.vercel.app/fr/examples/built-in-utilities/hocs

https://github.com/UnlyEd/next-right-now

**Comment by rajinwonderland** [comment]
This is awesome @Vadorequest! 
Would be great to showcase on the readme too! (if you're be cool with it)

Also, any feedback that would improve the package would be greatly appreciated!

**Comment by Vadorequest** [comment]
Regarding feedback, maybe you could look at the code I wrote using your lib and tell me if you think something could/should be improved?

For instance:
- Demo: https://nrn-v2-mst-aptd-at-lcz-sty-c1.vercel.app/fr/examples/built-in-features/static-i18n
- Code: https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-at-lcz-sty/src/pages/%5Blocale%5D/examples/built-in-features/static-i18n.tsx

What would you like to happen on the README?

**Comment by Vadorequest** [comment]
@rajinwonderland FYI I noticed today the 0.0.8 version made my `Code` text align inc center, I feel like the prop `codeBlockStyle` doesn't work anymore.

**Comment by rajinwonderland** [comment]
Good catch! I think the `codeBlockStyle` prop wasn't implemented correctly in the new update. For now @Vadorequest, I believe `codeContainerStyle` is really the only prop that takes in styling. 

I'll see if I can fix this in the next release.

**Comment by Vadorequest** [comment]
And, one suggestion I have is about **spaces**.

When I copy/paste a block of code, I also copy the code indentation for that file, and I don't like it to be "on the left" of the file (see below), but I like it indented as it should be if it was actual code. But this adds unnecessary spaces in front of each line. 🤔 

It's no big deal, but maybe there is a way to remove useless spaces in front of each line automatically? 

Source code using `Code`:
![image](https://user-images.githubusercontent.com/3807458/93688110-b4f8ea80-fac3-11ea-8c39-8d94086dd579.png)


Result:
![image](https://user-images.githubusercontent.com/3807458/93688100-9b57a300-fac3-11ea-89ec-a050b4b22255.png)

**Comment by rajinwonderland** [comment]
@Vadorequest I just saw you other post too! I'll take a look at your implementation and give some feedback. 

Regarding the readme, I'll add a section for **Showcase** and if I could add your site into it I'd really appreciate it!!!

**Comment by Vadorequest** [comment]
> Good catch! I think the `codeBlockStyle` prop wasn't implemented correctly in the new update. For now @Vadorequest, I believe `codeContainerStyle` is really the only prop that takes in styling.
> 
> I'll see if I can fix this in the next release.

Alright, thanks for the very fast feedback!

Which one should I use to style how the code is shown? I can change the implementation to use `codeContainerStyle` but if it's a bug then I better just write my style in both for now, so that I don't suffer another silent visual regression next time I upgrade.

**Comment by rajinwonderland** [comment]
@Vadorequest I can look into the spaces issue on copy as well. 

For now I'd suggest doing that. At least until I get the next release out which will probably be in the next few days 👍
