### ISSUE TITLE
Error: Language html not supported

### ISSUE THREAD

**Issue by hsyyid** [rajinwonderland/react-code-blocks#17]
I see it says html is a supported language, but I'm getting an error when trying to use it with a `CopyBlock`

Seems to happen when I have improper syntax in the code block. Test with the following (missing quote)
```html
<a href="https://google.com>Hello World</a>
```

```
Node v10.8.0
react-code-blocks@0.0.8
react ^16.12.0
```

**Comment by rajinwonderland** [comment]
Hey @hsyyid! 

I have to clarify this in the docs, but use __`markup`__ instead of `html` on the `language` prop and you're good to go.
```js
<CopyBlock
  language="markup"
   {...rest}
```
Going to close this for now.
Please refer to issue #5 for more details!
