### ISSUE TITLE
"shell" is not supported

### ISSUE THREAD

**Issue by lawrenceching** [rajinwonderland/react-code-blocks#19]
Hi
I saw the shell is supported in this page:
https://github.com/rajinwonderland/react-code-blocks/blob/master/LANGUAGES.md

But it gave me this error

```
Unhandled Rejection (Error): Language shell not supported
```

![image](https://user-images.githubusercontent.com/12114025/96335165-0e474000-10a9-11eb-98dc-84400cb17e2f.png)

"bash" is working ok.
Would it be a typo in the document?
Where is the gold source of all supported language list?

Thanks in advanced

**Comment by lawrenceching** [comment]
Reading your code, I saw you're using Prism highlighter by default

```tsx
// https://github.com/rajinwonderland/react-code-blocks/blob/master/packages/react-code-blocks/src/components/Code.tsx#L2

import React, { PureComponent } from 'react';
import { PrismAsyncLight as SyntaxHighlighter } from 'react-syntax-highlighter';
import { applyTheme } from '../utils/themeBuilder';
```

And you normalized the bash to shell

```tsx
// https://github.com/rajinwonderland/react-code-blocks/blob/master/packages/react-code-blocks/src/utils/normalizeLanguage.ts#L67-L70

{
    name: 'Shell',
    alias: ['shell', 'bash', 'sh', 'ksh', 'zsh'],
    value: 'shell',
  },
```

And then I checkout the react-syntax-highlighter
https://github.com/react-syntax-highlighter/react-syntax-highlighter/tree/master/src/languages/prism

It looks like Prism support bash instead of shell.
However, hljs supports both bash and shell.

**Comment by rajinwonderland** [comment]
Great catch @lawrenceching I'll go ahead and fix this!

**Comment by thesobercoder** [comment]
Is this fixed? I'm still getting the error.

**Comment by SebasG22** [comment]
I'm getting the same error but with `html`.
Language html not supported
Hopefully, a fix should be on the way.

**Comment by rajinwonderland** [comment]
@SebasG22 try using `markup` instead of `html`! Here's a [previous issue](https://github.com/rajinwonderland/react-code-blocks/issues/5#issuecomment-683479214) for further clarification

@thesobercoder @lawrenceching I'll be hopefully free this weekend to push a new release! 🤞 

Always accepting PRs too!

**Comment by mat250** [comment]
Hi @rajinwonderland, I tried this weekend to push a PR to you to fix it, but I was unable to fork the repo and make it worked on my laptop. 
Are there any requirements or pre-build operations to do to make this project work locally ?

For example, I had some trouble with the command `yarn workspace` command.

**Comment by rajinwonderland** [comment]
Hey @mat250 sorry for answering so late!

You want to:

## Install Dependencies
```sh
yarn
```

## Start Storybook
```sh
yarn pkg storybook 
```

## Build the Package
```sh
yarn pkg build
```

## Watch the package
```
yarn pkg start
```


## Preview on Demo
```sh
yarn start:demo
```

or

```sh
yarn demo start
```

## Submit PR

🎉🎉🎉🎉


Let me know if this helps!

**Comment by bofeiw** [comment]
This issue still occurs in version 0.0.8 published in npm.
