### ISSUE TITLE
Alignment issue when combining CopyBlock and showLineNumbers

### ISSUE THREAD

**Issue by rob4neo** [rajinwonderland/react-code-blocks#2]
Version: react-code-blocks@0.0.7
React Version: react@16.12.0
Browser: Chrome/79.0.3945.88 (Mac OS 10.15)

First of all, great project - exactly what I was looking for!

Unfortunately, when setting `showLineNumbers={true}` on a `CopyBlock`, the whole block gets knocked down to below the line numbers.

![Screenshot 2020-01-06 at 16 46 24](https://user-images.githubusercontent.com/52421116/71833054-1c8d1800-30a4-11ea-90da-b9770f16d534.png)

Code used (after using `create-react-app` and removing most of the default css styles):

```
//App.css
.App {
  width: 800px;
  margin: 0 auto;
  margin-top: 30px;
}
```
```
//App.js
import React from 'react';
import './App.css';
import { CopyBlock, dracula } from 'react-code-blocks'

const javascriptSnippet = `function toBe() {
  if (Math.random() < 0.5) {
    return true;
  } else {
    return false;
  }
}`;

function App() {
  return (
    <div className="App">
      <CopyBlock
        language='javascript'
        showLineNumbers={true}
        text={javascriptSnippet}
        theme={dracula}
      />
    </div>
  );
}

export default App;
```

**Comment by rajinwonderland** [comment]
Hey @rob4neo! Thanks! I had no idea people were using this lol 😅 

I'll look into this right away!

**Comment by rob4neo** [comment]
Yeah totally! I needed something that could do syntax highlighting, line numbers and also copy-paste all in one - this was the only solution I could find that provided all of that out of the box. Alas, the issue above prevented me from using it in the end.

**Comment by mattvb91** [comment]
same issue here

**Comment by Vadorequest** [comment]
Same issue, I used the other component to work around the issue.

@rajinwonderland FYI we use your component in https://github.com/UnlyEd/next-right-now/pull/52

WIP demo: https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-awco7i3cr.now.sh/fr

**Comment by sean9keenan** [comment]
Wanted to second this project being exactly what I was looking for! (and also running into this issue)

I remember looking for a project like this about a year and a half ago, not finding one - then searching again and being pleasantly surprised to find this!

At first glance, it looks like the two `<code>` blocks aren't getting styled _at all_. [Digging through the code a tiny amount](https://github.com/rajinwonderland/react-code-blocks/blob/master/packages/react-code-blocks/src/components/CopyBlock.js#L60) it looks like this is just confusion re: the `codeBlock` boolean that you can pass in to a CopyBlock component. Altering the above example:
```
function App() {
  return (
    <div className="App">
      <CopyBlock
        language='javascript'
        showLineNumbers={true}
        text={javascriptSnippet}
        theme={dracula}
      />
    </div>
  );
}
```

Wanted to say how much I appreciate this project, looking forward to using it more!

**Comment by rajinwonderland** [comment]
Hey @Vadorequest @sean9keenan that's awesome! Honestly I haven't had much time to maintain this and would love for some help. 

I've just release a couple of new versions that migrates the current repo to typescript. Hoping to resolve the styling issues by implementing something like @theme-ui or @styled-system. 

Stay tuned!

**Comment by rajinwonderland** [comment]
@rob4neo here's a [demo](https://codesandbox.io/s/autumn-wind-8itrc?file=/src/App.js) with  v0.0.8-beta version. By adding a `codeBlock` prop to the component, the alignment looks weird. 

I think it was defaulting before to an inline `Code` component, which generally doesn't look great with lineNumbers.

The new v0.0.8 also has a `customStyle` prop too should you run into any issues!

Let me know if this is still an issue!
