### ISSUE TITLE
Error: Language html not supported

### ISSUE THREAD

**Issue by sdserage** [rajinwonderland/react-code-blocks#21]
`react-code-blocks@0.0.8`

Downloaded this library because it looked great for the project I'm working on. Unfortunately ran into this error:

<img width="974" alt="Screen Shot 2020-12-09 at 11 37 43 AM" src="https://user-images.githubusercontent.com/31323515/101643759-38670f80-3a13-11eb-95be-4753c9c37c96.png">

For now I can use the language 'jsx' for what I need to do but it would be nice to have 'html' available. I tried 'html5' and 'HTML' just incase it was a name thing or something but nothing worked.

**Comment by rajinwonderland** [comment]
Hey @sdserage!

I have to clarify this in the docs, but use markup instead of html on the language prop and you're good to go.

<CopyBlock
  language="markup"
   {...rest}
Going to close this for now.
Please refer to issue #5 for more details!
