### ISSUE TITLE
Netlify demo returns 404 code

### ISSUE THREAD

**Issue by bleszerd** [rajinwonderland/react-code-blocks#22]
Netlify demo example on README.md return not found for https://app.netlify.com/sites/react-code-blocks/deploys

**Comment by rajinwonderland** [comment]
Hey @bleszerd, I think the link you're looking for was hyperlinked on the [Demo](https://react-code-blocks.netlify.app/) section of the readme. 

Here it is for reference:
https://react-code-blocks.netlify.app/
