### ISSUE TITLE
Code block rendering inline-block in .tsx

### ISSUE THREAD

**Issue by daviavmello** [rajinwonderland/react-code-blocks#26]
I'm using @vercel to ship a pretty simple .tsx app and for some reason, it renders as inline instead of code block. Here's my code:

`const toggleCodeTheme = (window.innerWidth) < 1000 ? hybrid : github;`
    ` <CopyBlock
        language="javascript"
        text={iterative}
        codeBlock
        theme={toggleCodeTheme}
        showLineNumbers={false}
      />`

**Comment by daviavmello** [comment]
![Screen Shot 2021-02-17 at 6 24 21 PM](https://user-images.githubusercontent.com/51424368/108281924-b865d000-714e-11eb-94d3-3a031b7b7684.png)
![Screen Shot 2021-02-17 at 6 24 01 PM](https://user-images.githubusercontent.com/51424368/108281927-b8fe6680-714e-11eb-9565-a189d210f4be.png)

LocalHost vs. live

**Comment by rajinwonderland** [comment]
Hey @daviavmello, thanks for submitting the issue!

I noticed that you're using a variable `iterative` to input the text for your `CopyBlock`.

Do you know if those variables are being generated at runtime or are the being statically built? 

If they're being generated at runtime, I think NextJS might be rendering the block as empty text prior to receiving the `iterative` variable making it appear as though it were inline. 

You might want to try using [`getServerSideProps`](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) or [`getStaticProps`](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) in that case. 

Let me know if you need more clarification should this be the case! 👍 

If that isn't the case, I'll need a bit more context on the how the component is being rendered to debug.

**Comment by daviavmello** [comment]
Hi @rajinwonderland, thank you for your response. I'm only using @vercel as the host. and not using Next.js. I just deployed it to Netlify and it seems that I'm having the same issue. 

https://fibonacci-daviavmello.netlify.app/

**Comment by rajinwonderland** [comment]
Gotcha @daviavmello and no problem!

Are you using `create-react-app`, `gatsby`, or something else?

Also, are you using it with `mdx` by any chance?

**Comment by daviavmello** [comment]
@rajinwonderland yes, I'm using `create-react-app`.

**Comment by rajinwonderland** [comment]
Sweet! Ok so when I debugged the netlify site, I noticed that you were passing in the functions `iterative` and `recursive` into the `text` prop.

From what I could gather, it seemed like these variables were being passing as a `function` instead of a `string` in which case that might cause some issues. 


Can you try stringifying them like so:

> I've made a [codesandbox here](https://codesandbox.io/s/react-code-blocks26-zh9qp?file=/src/App.js) using `create-react-app` too that demos this in action (although it's not using typescript)


```jsx
import "./styles.css";
import { CopyBlock, github, hybrid } from "react-code-blocks";
import { recursive } from "./Recursive";
import { iterative } from "./Iterative";

export default function App() {
  const toggleCodeTheme = window.innerWidth < 1000 ? hybrid : github;

  return (
    <div className="App">
      <h1>
        <a href="https://github.com/rajinwonderland/react-code-blocks">
          <pre className="rcb">react-code-blocks</pre>
        </a>
        <a
          href="https://github.com/rajinwonderland/react-code-blocks/issues/26"
          target="_blank"
        >
          Issue #26
        </a>
      </h1>
      <h2>Recursive Example</h2>
      <CopyBlock
        showLineNumbers={false}
        theme={toggleCodeTheme}
        text={recursive.toString()}
        language="javascript"
        codeBlock
      />
      <br />
      <h2>Iterative Example</h2>
      <CopyBlock
        showLineNumbers={false}
        theme={toggleCodeTheme}
        text={iterative.toString()}
        language="javascript"
        codeBlock
      />
    </div>
  );
}
```

**Comment by rajinwonderland** [comment]
Sweet @daviavmello!


Ok so when I debugged the netlify site, I noticed that you were passing in the functions `iterative` and `recursive` into the `text` prop.

From what I could gather, it seemed like these variables were being passing as a `function` instead of a `string` in which case that might cause some issues. 



Can you try stringifying them like so:

> I've made a [codesandbox here](https://codesandbox.io/s/epic-cloud-58p1p?file=/src/App.js) using `create-react-app` too that demos this in action (although it's not using typescript)


```jsx
 <CopyBlock
        showLineNumbers={false}
        theme={toggleCodeTheme}
        text={`function recursive(arrLength) {
        var t0 = performance.now();
        var firstNum = arr[arr.length - 2];
        var secondNum = arr[arr.length - 1];
        var nNum = firstNum + secondNum;
        arr.push(nNum);
        firstNum = secondNum;
        secondNum = nNum;
      
        if (arr.length < arrLength) {
          recursive(arrLength);
        }
      
        var t1 = performance.now();
        return (t1 - t0) * 1000;
      }`}
        language="javascript"
        codeBlock
      />
   ```

What's happening is that post build, the stringified function is being minified and converted into vanilla js post build. So you end up with your functions looking something like this:

```js
e=>{const t=performance.now();let c=i[i.length-2],n=i[i.length-1],r=c+n;i.push(r),c=n,n=r,i.length<e&&l(e);return 1e3*(performance.now()-t)}
```

Instead of this:

```js
function recursive(arrLength) {
        var t0 = performance.now();
        var firstNum = arr[arr.length - 2];
        var secondNum = arr[arr.length - 1];
        var nNum = firstNum + secondNum;
        arr.push(nNum);
        firstNum = secondNum;
        secondNum = nNum;
      
        if (arr.length < arrLength) {
          recursive(arrLength);
        }
      
        var t1 = performance.now();
        return (t1 - t0) * 1000;
  }
  ```

**Comment by rajinwonderland** [comment]
Here's a [deployed netlify version](https://rcb-issue-26.netlify.app/) for reference and a separate [repo](https://github.com/rajinwonderland/rcb-issue-26) for reference as well @daviavmello!

Let me know if this solves your issue!

![image](https://user-images.githubusercontent.com/15880596/108291138-9700e600-7146-11eb-967f-943442313fed.png)

**Comment by daviavmello** [comment]
@rajinwonderland thank you for debugging this for me. I tried to force stringify it without success. I did not want to hardcode it into the prop, but for time reasons I went with your solution. I appreciate your project.
