### ISSUE TITLE
Clickable Link

### ISSUE THREAD

**Issue by codingwithdidem** [rajinwonderland/react-code-blocks#27]
Hi. Is it possible to add an actual clickable link to the code string?

  const code = `const instagram = 'https://www.instagram.com/didemk95/'; 
const a = <a href=\"http://www.example.com\">here</a>`

I want them to be clickable

**Comment by rajinwonderland** [comment]
Hey @codingwithdidem, you can wrap the `CodeBlock` components in a `div` like so:


```
<div onClick={() => someFunction()}>
    <CodeBlock 
        ...
    />
</div>
```

**Comment by codingwithdidem** [comment]
Hey @rajinwonderland  thank you! :)

**Comment by rajinwonderland** [comment]
Anytime!
