### ISSUE TITLE
move typescript-plugin-styled-components to devDependencies

### ISSUE THREAD

**Issue by florpor** [rajinwonderland/react-code-blocks#28]
it is currently under dependencies, but should only be needed for dev (as far as i understand).

currently since it is a normal dependency of the package it is messing my project's dependency tree since the project is using typescript 4 while the installed `typescript-plugin-styled-components@1.4.4` requires `typescript@^2.5.2 || ^3.0`.

**Comment by rajinwonderland** [comment]
Thanks for catching this @florpor. If you'd like to submit a pull request, I'd very much appreciate it! Otherwise, I'll certainly reflect this on a future release! 👍
