### ISSUE TITLE
Correctly associate MIT license on npm

### ISSUE THREAD

**Issue by rezaabedian** [rajinwonderland/react-code-blocks#3]
Hello,

Thank you for the hard work that has been put into this library. 

The library has an MIT license on GitHub, but on the npm is listed as having no license. As a result this is causing our internal tooling to reject onboarding this library for consumption in our organisation. Can you kindly address this?

Thank you!

**Comment by rajinwonderland** [comment]
Hey @rezaabedian, sorry for the delay. Just added the licensing to v0.0.8-alpha!
