### ISSUE TITLE
csharp highlighting not working on Chrome 92.0 with 0.0.8

### ISSUE THREAD

**Issue by umermansoor** [rajinwonderland/react-code-blocks#48]
The C# code is not highlighted with `csharp`. Rest are working fine. 
Tried on an older Firefox browser and csharp code looked fine on it
Using it with React 17

**Comment by rajinwonderland** [comment]
Thanks for the issue @umermansoor, looking into this today. The package hasn't been updated in a while so a lot of the dependencies (react included) are pretty stale. Should have an answer for you soon!

**Comment by thomasmost** [comment]
Non-repro
