### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by vahnag** [rajinwonderland/react-code-blocks#51]
I want to use the [soft wrap long lines](https://github.com/rajinwonderland/react-code-blocks/commit/1dd2799c89bbe1ce318f8d88ebf10747dd247b4e) feature that is implemented back in June but not published to npm. 

Could you please publish a new version with the latest changes?

**Comment by rajinwonderland** [comment]
Hey @vahnag, sorry for the late response. I will be releasing hopefully today if I can get some extra time (latest by the end of the week)! Appreciate the ping!

**Comment by SugarSpike** [comment]
@rajinwonderland So... any update on that publish? ;)
