### ISSUE TITLE
Vulnerability of dependency

### ISSUE THREAD

**Issue by crow7m** [rajinwonderland/react-code-blocks#52]
Thank you for the great package, 
I have noticed that Prismjs has v 1.23 is marked as hight vulnerability, 
![image](https://user-images.githubusercontent.com/10707009/132977711-b2be3f72-cc86-493f-ad04-90b89d2b8213.png)
This was patched in v1.24 can the react-code-blocks be updated to use the latest prism version ? thank you

**Comment by rajinwonderland** [comment]
Thanks for the heads up @crow7m, will setup a resolution for this on the next release!

**Comment by mallockey** [comment]
Hi @rajinwonderland has react-code-blocks been updated yet to remove this vulnerability?

**Comment by ozgur-dogan** [comment]
What is the expected release date for this patch?

**Comment by esciafardini** [comment]
Any word?

**Comment by snpranav** [comment]
Any updates on this? It's been over a year now.

**Comment by thomasmost** [comment]
Hey all, these should be resolved in 0.1.2 (latest)
