### ISSUE TITLE
Custom component for copy button

### ISSUE THREAD

**Issue by fandy** [rajinwonderland/react-code-blocks#54]
Would be great if we could pass in a custom component if the icon that's used by default doesn't suit the design. :)

**Comment by crow7m** [comment]
Good morning, is there a plan to implement this, or could you please specify the way to replace the default copy icon ?

**Comment by rasametdoner** [comment]
Hello, 
I had a same issue and wanted to replace the image of copy button. I tried to write some CSS. Maybe it might be also helpful for you guys. Here is an example:

button > .icon {
  background-image: url('data:image/svg+xml;base64,PCEtLSBSZXBsYWNlIHRoZSBjb250ZW50cyBvZiB0aGlzIGVkaXRvciB3aXRoIHlvdXIgU1ZHIGNvZGUgLS0+Cgo8c3ZnIHJvbGU9ImltZyIgdmlld0JveD0iMCAwIDI0IDI0IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxwYXRoIGQ9Ik0wIDBoMjR2MjRIMFYwem0yMi4wMzQgMTguMjc2Yy0uMTc1LTEuMDk1LS44ODgtMi4wMTUtMy4wMDMtMi44NzMtLjczNi0uMzQ1LTEuNTU0LS41ODUtMS43OTctMS4xNC0uMDkxLS4zMy0uMTA1LS41MS0uMDQ2LS43MDUuMTUtLjY0Ni45MTUtLjg0IDEuNTE1LS42Ni4zOS4xMi43NS40Mi45NzYuOSAxLjAzNC0uNjc2IDEuMDM0LS42NzYgMS43NTUtMS4xMjUtLjI3LS40Mi0uNDA0LS42MDEtLjU4Ni0uNzgtLjYzLS43MDUtMS40NjktMS4wNjUtMi44MzQtMS4wMzRsLS43MDUuMDg5Yy0uNjc2LjE2NS0xLjMyLjUyNS0xLjcxIDEuMDA1LTEuMTQgMS4yOTEtLjgxMSAzLjU0MS41NjkgNC40NzEgMS4zNjUgMS4wMiAzLjM2MSAxLjI0NCAzLjYxNiAyLjIwNS4yNCAxLjE3LS44NyAxLjU0NS0xLjk2NiAxLjQxLS44MTEtLjE4LTEuMjYtLjU4Ni0xLjc1NS0xLjMzNmwtMS44MyAxLjA1MWMuMjEuNDguNDUuNjg5LjgxIDEuMTA5IDEuNzQgMS43NTYgNi4wOSAxLjY2NiA2Ljg3MS0xLjAwNC4wMjktLjA5LjI0LS43MDUuMDc0LTEuNjVsLjA0Ni4wNjd6bS04Ljk4My03LjI0NWgtMi4yNDhjMCAxLjkzOC0uMDA5IDMuODY0LS4wMDkgNS44MDUgMCAxLjIzMi4wNjMgMi4zNjMtLjEzOCAyLjcxMS0uMzMuNjg5LTEuMTguNjAxLTEuNTY2LjQ4LS4zOTYtLjE5Ni0uNTk3LS40NjYtLjgzLS44NTUtLjA2My0uMTA1LS4xMS0uMTk2LS4xMjctLjE5NmwtMS44MjUgMS4xMjVjLjMwNS42My43NSAxLjE3MiAxLjMyNCAxLjUxNy44NTUuNTEgMi4wMDQuNjc1IDMuMjA3LjQwNS43ODMtLjIyNiAxLjQ1OC0uNjkxIDEuODExLTEuNDExLjUxLS45My40MDItMi4wNy4zOTctMy4zNDYuMDEyLTIuMDU0IDAtNC4xMDkgMC02LjE3OWwuMDA0LS4wNTZ6Ii8+Cjwvc3ZnPg=='); 
  fill: none;
  background-position: center;
  backgorund-repeat: no-repeat;
}

**Comment by siddharthachoubey13** [comment]
Please add a way to customize the icon.

**Comment by Arttistzys** [comment]
Try this.

`
import { useEffect } from "react";
import ReactDOM from 'react-dom';
import { ReactComponent as CopyIcony } from '../../assets/copy-icon.svg'
...
  useEffect(() => {
    const codeBlockCopyElement = document.querySelectorAll('#code-block-copy');
    console.log("Here is svg element : ", codeBlockCopyElement)
    if (codeBlockCopyElement && codeBlockCopyElement?.length) {
      codeBlockCopyElement.forEach((element) => {
        const svgElement = element.querySelector('svg');
        console.log("Here is svg element : ", svgElement)
        if (svgElement) {
          // Create a container for the new SVG React component
          const container = document.createElement('div');
          container.style = 'padding-top: 1.5px;'
          svgElement.replaceWith(container);
  
          // Render the React component into the container
          ReactDOM.render(<CopyIcony />, container);
        }
      })
      
    }
  }, []);
  ...
  
  <div style={{ marginTop: 10, marginBottom: 10 }} id={"code-block-copy"}>
                      <CopyBlock
                        text={lang.code}
                        language={findSupportedLanguage(
                          lang.language || lang.title
                        )}
                        theme={atomOneLight}
                        codeBlock
                        onCopy={() => onCopy(lang.code)}
                      />
                    </div>
                    
                    ...
`
