### ISSUE TITLE
Need way to constrain height / add a scrollbar

### ISSUE THREAD

**Issue by zontreck** [rajinwonderland/react-code-blocks#7]
By default it appears that it expands to the code snippet's entire length. This is not ideal for large snippets of code you need to place inside a block while still making the webpage look nice.

**Comment by rajinwonderland** [comment]
Hey @zontreck , two ways you can achieve this!

You can wrap a code block inside a container and constrain it's properties like so:

```jsx
const MyComp = () => (
  <div style={{ height: '200px', overflowY: 'auto' }}>
    <CodeBlock text="hello world"  showLineNumbers />
  <div>
```
> You can do this on any version! 😄 

The alternative would be to upgrade to v0.0.8 and use the `customStyle` prop, a demo of which I've added onto the [CodeBlock's Story for your use-case here](https://react-code-blocks.rajinwonderland.vercel.app/?path=/docs/codeblock--add-a-scrollbar)

> Please note upgrading to the v0.0.8 release require node >= 12!

Let me know if you have any more questions!
