### ISSUE TITLE
this not working with my react native app!!

### ISSUE THREAD

**Issue by patel-harshal** [rajinwonderland/react-code-blocks#73]
this not properly working with my react native app he got error in my android application "s.default.button is not a function. (In 's.default.button(k(),(function(e){return e.theme.backgroundColor}),(function(e){return e.copied?1:.5}))', 's.default.button' is undefined)"

**Comment by thomasmost** [comment]
react-native is currently out of our scope of support. If you would like to contribute to add support for this, we'd welcome that, but it's not in my expertise
