### ISSUE TITLE
Line numbers issue

### ISSUE THREAD

**Issue by aprisniak** [rajinwonderland/react-code-blocks#8]
Hi, I have an issue with line numbers.

It is probably a bug.

```jsx
<CopyBlock
  text={'var a = 10;\nconsole.log(a);'}
  language="javascript"
  theme="dracula"
  wrapLines
  codeBlock
/>
```

```html
<span linenumbercontainerstyle="[object Object]"></span>
```

Warning: React does not recognize the `lineNumberContainerStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `linenumbercontainerstyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by rajinwonderland** [comment]
Hey @aprisniak, please upgrade to v0.0.8! Please note that this release require node >= 12!

Let me know if the problem still persists!

**Comment by aprisniak** [comment]
Fixed!
