### ISSUE TITLE
Update some packages used

### ISSUE THREAD

**Issue by lritter79** [rajinwonderland/react-code-blocks#82]
<img width="586" alt="Screen Shot 2023-06-05 at 7 43 11 AM" src="https://github.com/rajinwonderland/react-code-blocks/assets/12736541/20fdb7e2-1347-435d-8ef2-fb5c3b653c58">
<img width="593" alt="Screen Shot 2023-06-05 at 7 43 20 AM" src="https://github.com/rajinwonderland/react-code-blocks/assets/12736541/e37caf81-8771-4081-82b2-9798c94b9af3">
Ran `yarn audit` in the project I use react-code-blocks in and it has some dependencies that need to be upgraded.

**Comment by millieseow123** [comment]
Hi @rajinwonderland, any updates on this? My project requires those dependencies to be upgraded as well. Thanks!

**Comment by thomasmost** [comment]
Hi @millieseow123 and @lritter79 — this should be resolved now, though if you are using a custom feed you may want to wait til #85  is resolved to update
