### ISSUE TITLE
Copy button should not be of type="submit"

### ISSUE THREAD

**Issue by tpkiddle** [rajinwonderland/react-code-blocks#9]
If I place a code block within a form clicking the copy button submits the form. This is bad. 

The copy button type attribute should be type="button"

**Comment by rajinwonderland** [comment]
Good catch, I'll go ahead and make that change! 👍

**Comment by rajinwonderland** [comment]
Hey @tpkiddle, please upgrade to v0.0.8! Note that this release requires node version >= 12!
